apiVersion: apps/v1
kind: Deployment
metadata:
  name: searcher
spec:
  template:
    spec:
      containers:
      - name: searcher
        securityContext:
          # Required to prevent escalations to root.
          allowPrivilegeEscalation: false
          runAsUser: 100
          runAsGroup: 101
          readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /tmp
              name: tmpdir
      - name: jaeger-agent
        securityContext:
          # Required to prevent escalations to root.
          allowPrivilegeEscalation: false
          runAsUser: 100
          runAsGroup: 101
          readOnlyRootFilesystem: true
      volumes:
      - emptyDir: {}
        name: tmpdir
