apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  template:
    spec:
      containers:
      - name: minio
        securityContext:
          # Required to prevent escalations to root.
          allowPrivilegeEscalation: false
          runAsUser: 100
          runAsGroup: 101
        volumeMounts:
          - name: minio
            mountPath: /minio
      securityContext:
        runAsUser: 100
        runAsGroup: 101      
        fsGroup: 101
        fsGroupChangePolicy: "OnRootMismatch"            
      volumes:
      - emptyDir: {}
        name: minio