apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  template:
    spec:
      containers:
      - name: prometheus
        securityContext:
          # Required to prevent escalations to root.
          allowPrivilegeEscalation: false
          runAsUser: 100
          runAsGroup: 100
          readOnlyRootFilesystem: true
      securityContext:
        fsGroup: 100
        fsGroupChangePolicy: "OnRootMismatch"