apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patchesStrategicMerge:
  - frontend/sourcegraph-frontend.Deployment.yaml
  - gitserver/gitserver.StatefulSet.yaml
  - grafana/grafana.StatefulSet.yaml
  - minio/minio.Deployment.yaml
  - indexed-search/indexed-search.StatefulSet.yaml
  - prometheus/prometheus.Deployment.yaml
  - redis/redis-cache.Deployment.yaml
  - redis/redis-store.Deployment.yaml
  - searcher/searcher.Deployment.yaml
