apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgsql
spec:
  template:
    spec:
      initContainers:
      - name: correct-data-dir-permissions
        securityContext:
          # Required to prevent escalations to root.
          allowPrivilegeEscalation: false
          runAsUser: 999
          runAsGroup: 999
          readOnlyRootFilesystem: true
      containers:
      - name: pgsql
        securityContext:
          # Required to prevent escalations to root.
          allowPrivilegeEscalation: false
          runAsUser: 999
          runAsGroup: 999
          readOnlyRootFilesystem: true
        volumeMounts:
            - mountPath: /var/run/postgresql
              name: lockdir          
      securityContext:
        # Required to prevent escalations to root.
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
        fsGroupChangePolicy: "OnRootMismatch"        
      volumes:
      - emptyDir: {}
        name: lockdir 

