apiVersion: apps/v1
kind: Deployment
metadata:
  name: sourcegraph-frontend
spec:
  template:
    spec:
      containers:
      - name: frontend
        securityContext:
          # Required to prevent escalations to root.
          allowPrivilegeEscalation: false
          runAsUser: 100
          runAsGroup: 101
          readOnlyRootFilesystem: true
        volumeMounts:
          - name: home-dir
            mountPath: /home/sourcegraph
      - name: jaeger-agent
        securityContext:
          # Required to prevent escalations to root.
          allowPrivilegeEscalation: false
          runAsUser: 100
          runAsGroup: 101
          readOnlyRootFilesystem: true
      volumes:
      - emptyDir: {}
        name: home-dir
