apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-proxy
spec:
  template:
    spec:
      containers:
      - name: github-proxy
        securityContext:
          # Required to prevent escalations to root.
          allowPrivilegeEscalation: false
          runAsUser: 100
          runAsGroup: 101
          readOnlyRootFilesystem: true
      - name: jaeger-agent
        securityContext:
          # Required to prevent escalations to root.
          allowPrivilegeEscalation: false
          runAsUser: 100
          runAsGroup: 101
          readOnlyRootFilesystem: true
